### PR TITLE
For Toolkit #44051 update metric logging

### PR DESCRIPTION
**Pull request by nmontmarquette**
As mentioned, Kerby accepted to quickly testout running Flame, on my side, I'll verify what comes out on the Amplitude Website.

Thank you Kerby.

### CODE REVIEW

**Comment by nmontmarquette** [comment]
Righ! Thank you for reminding me.
Is the check order ok ? SHOTGUN_FLAME_VERSION before TOOLKIT_FLAME_VERSION?

**Comment by nmontmarquette** [comment]
For @josh-t here is a Metric sample from the Amplitude website as tested by Kerby:
```
"event_properties": { "Engine": "tk-flame", "Engine Version": "v1.9.8", "Host App": "Flame", "Host App Version": "2018.3.pr84", "event_group": "Toolkit", "event_name": "Launched Software", "event_type": "event", "from_api": true }
```

**Comment by nmontmarquette** [comment]
@krbg with almost ready to merge, can I ask you to test it out just once more? Thank you.

**Comment by krbg** [comment]
Sorry for the late reply. Please tell me when you are ready.

**Pull request merged**
